name: master

on:
  push:
    branches:
      - master

jobs:

  #--------------------------
  # BUILD
  #--------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.3.10

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: |
          flutter analyze
